### PR TITLE
Make entity guid assignment explicit

### PR DESCRIPTION
**Pull request by sprucely**
This fixes the exception:
```System.InvalidOperationException: Unable to track an entity of type ... because primary key property Id is null.```

### CODE REVIEW

**Comment by sprucely** [comment]
@srkirkland I've been trying to understand how these Ids even work. They are not db-generated, yet I could find no C# code that generates them. Could it possibly be that ALL of these sections of code impacted by this PR are not actually being used in production?

I would vote for updating the table columns to have a default unique identifier (perhaps using UDF if the identifier can't be directly assigned to a nvarchar column.) And then use the `DatabaseGenerated` attribute.

**Comment by srkirkland** [comment]
@sprucely I'm not sure but one article i read suggested that old EF Core would auto generate the IDs for you, but new EF Core will not (and throws that error you sent).  So if that's really the case I would agree with you to have the columns default to a uniqueID and use database generated (either the attribute or the fluent mapping).  I'm not sure about the nvarchar though, that might be a wrinkle.  I think it's be worth changing to a unique identifier column type and seeing if that messes anything up.

**Comment by srkirkland** [comment]
@sprucely now that i look at it a bit more, there are lots of places in the app where John already was going Guid.NewGuid() in code, so maybe it is worth just adding it everywhere?  Doesn't seem like that we'd want to do if we had another option though, seems really easy to miss and have stuff not work just like this.

**Comment by sprucely** [comment]
@srkirkland An easy compromise between modifying the db column definitions and requiring explicit creation of Ids in code is to generate them in the entity constructors.

**Comment by sprucely** [comment]
Oh, and that option is already being done in ApiKey constructor.

**Comment by srkirkland** [comment]
@sprucely that's probably the best option then for now, let's go with that way and check that it works.  For future projects we should probably just use the right column type and have the db generate, if we decide to go with guids.

**Comment by sprucely** [comment]
Yep. I think it's catching on. I'm starting to see it used more in the wild.

**Pull request merged**
