### PR TITLE
Require https, not sure about the shrinkwrap

### PR DESCRIPTION
**Pull request by jSylvestre**

### CODE REVIEW

**Comment by jSylvestre** [comment]
Without this, it was giving me an error when logging in:

System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Review by sprucely — CHANGES_REQUESTED** [review]
Could you also make this one https?
https://github.com/ucdavis/Sloth/blob/480b483720ae7cd3126e927e64f977a031142303/Sloth.Web/Properties/launchSettings.json#L24

**Review by sprucely — APPROVED** [review]

**Review by srkirkland — APPROVED** [review]
next time don't check in the shrinkwrap change but otherwise 🚢

**Comment by jSylvestre** [comment]
Closing. Will make changes on Spruce's PR

**Pull request closed without merging**
