### PR TITLE
log to stackify if we have a stackify API Key

### PR DESCRIPTION
**Pull request by srkirkland**

### CODE REVIEW

**Review by sprucely — COMMENTED** [review]
What about logging configuration for jobs?

**Review by jSylvestre — APPROVED** [review]
Don't forget there is the web and api projects
And probably check the test ones too.

**Comment by srkirkland** [comment]
> What about logging configuration for jobs?

good point!

**Comment by srkirkland** [comment]
> Don't forget there is the web and api projects And probably check the test ones too.

I don't understand

**Review by sprucely — APPROVED** [review]

**Pull request merged**
